name: valet_parking_app
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  hive: ^2.2.3
  path_provider: ^2.1.2
  http: ^1.2.0
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  syncfusion_flutter_datepicker: ^24.2.6
  time_picker_spinner: ^0.0.1
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  syncfusion_flutter_barcodes: ^24.2.6
  webview_flutter: ^4.7.0
  social_share: ^2.3.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
